import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";

   const openSans = Open_Sans({
      subsets: ['latin'], // Specify desired character subsets for smaller file size
      display: 'swap',   // Use 'swap' for better perceived performance
    });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
    <html lang="en">
      <body
        className={` ${openSans.className} antialiased bg-slate-50`}

      >
        {children}
      </body>
    </html>
    </TRPCReactProvider>
  );
}
